name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Lint
        run: python -m ruff check --no-cache .
      - name: Install eodash catalog itself for tests
        run: python -m pip install .
      - name: Test
        run: cd tests && python -m pytest -p no:cacheprovider
