# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package and Docker image

on:
    push:
      tags:
      - '*'
jobs:
  deploy:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch
    - name: Build and publish
      env:
        HATCH_INDEX_USER: ${{ secrets.PYPI_USERNAME }}
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_PASSWORD }}
      run: |
        hatch build
        hatch publish
    - name: Build and push docker image
      run: |
        IMAGE_ID=ghcr.io/${{ github.repository }}
        VERSION=${{ github.ref_name }}
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        docker build -t $IMAGE_ID:latest -t $IMAGE_ID:$VERSION .
        docker push $IMAGE_ID:latest
        docker push $IMAGE_ID:$VERSION
